name = "backend"
main = "src/index.ts"
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "Text"
globs = ["**/*.csv"]
fallthrough = false

[assets]
directory = "../frontend/dist"
binding = "ASSETS"

[build]
command = "npm run build"

[observability]
enabled = true
